sonar.projectKey=2025-itcs383-arai-kor-dai_2025-itcs383-arai-kor-dai
sonar.organization=2025-itcs383-arai-kor-dai

sonar.sources=implementations/
sonar.tests=implementations/backend/__tests__

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Exclude unnecessary files
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.js

# Test coverage report
sonar.javascript.lcov.reportPaths=implementations/backend/coverage/lcov.info
