sonar.projectKey=2025-itcs383-arai-kor-dai_2025-itcs383-arai-kor-dai
sonar.organization=2025-itcs383-arai-kor-dai

sonar.sources=.

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Exclude unnecessary files
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.html,**/*.css

# Ignore coverage if no tests yet
sonar.coverage.exclusions=**/*
